export const mockPodcastWithEpisodesData = {
    "resultCount": 11,
    "results": [
        {
            "wrapperType": "track",
            "kind": "podcast",
            "collectionId": 1440300401,
            "trackId": 1440300401,
            "artistName": "Andrew Santino",
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "trackName": "Whiskey Ginger with Andrew Santino",
            "collectionCensoredName": "Whiskey Ginger with Andrew Santino",
            "trackCensoredName": "Whiskey Ginger with Andrew Santino",
            "collectionViewUrl": "https://podcasts.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?uo=4",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?uo=4",
            "artworkUrl30": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/30x30bb.jpg",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "artworkUrl100": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/100x100bb.jpg",
            "collectionPrice": 0.00,
            "trackPrice": 0.00,
            "collectionHdPrice": 0,
            "releaseDate": "2025-02-14T12:00:00Z",
            "collectionExplicitness": "notExplicit",
            "trackExplicitness": "explicit",
            "trackCount": 335,
            "trackTimeMillis": 4789,
            "country": "USA",
            "currency": "USD",
            "primaryGenreName": "Comedy",
            "contentAdvisoryRating": "Explicit",
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "genreIds": [
                "1303",
                "26"
            ],
            "genres": [
                "Comedy",
                "Podcasts"
            ]
        },
        {
            "previewUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC1203545240.mp3?updated=1740101246",
            "episodeUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC1203545240.mp3?updated=1740101246",
            "artistIds": [],
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "artworkUrl160": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/160x160bb.jpg",
            "episodeFileExtension": "mp3",
            "episodeContentType": "audio",
            "episodeGuid": "63bb56bc-eff1-11ef-8b67-9b0c1e71a16a",
            "trackId": 1000694722396,
            "trackName": "Rosebud Baker",
            "releaseDate": "2025-02-21T12:00:00Z",
            "shortDescription": "",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "closedCaptioning": "none",
            "collectionId": 1440300401,
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "kind": "podcast-episode",
            "wrapperType": "podcastEpisode",
            "description": "Rosebud Baker doesn’t pull punches—she lands them. With her razor-sharp wit and unflinching honesty, she’s become one of the most fearless voices in comedy. Her latest stand-up special, The Mother Lode, proves why she’s a powerhouse, delivering darkly hilarious takes on life, love, and everything in between. Beyond the stage, she’s bringing the heat in the writers' room at Saturday Night Live, shaping some of the sharpest comedy on TV. Whether she’s on stage or behind the scenes, Rosebud’s comedy is as bold as it is unforgettable.\n\n#rosebudbaker #andrewsantino #whiskeyginger #podcast\n\n============================================\n\nSponsor Whiskey Ginger: \nhttps://public.liveread.io/media-kit/whiskeyginger\n\nSUPPORT OUR SPONSORS\n\nSQUARESPACE\nGet that site up and running now!\n10% off your order\nhttps://squarespace.com/whiskey\n\nKICKOFF\nGET YOUR 1ST MONTH  FOR $1\nhttp://getkickoff.com/whiskey\n\nINDOCHINO\nPROMO CODE: WHISKEY\nGET 20% OFF $499 OR MORE\nhttps://indochino.com/\n\nNORD VPN\n4 MONTHS FREE WITH A 2 YEAR PLAN\nhttps://nordvpn.com/whiskey\n\n=======================================\n\nFollow Andrew Santino:\nhttps://www.instagram.com/cheetosantino/\nhttps://twitter.com/CheetoSantino\n\nFollow Whiskey Ginger:\nhttps://www.instagram.com/whiskeygingerpodcast\nhttps://twitter.com/whiskeygingerpodcast\n\nProduced and edited by Joe Faria\nhttps://www.instagram.com/itsjoefaria\nLearn more about your ad choices. Visit megaphone.fm/adchoices",
            "country": "USA",
            "collectionViewUrl": "https://itunes.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?mt=2&uo=4",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/rosebud-baker/id1440300401?i=1000694722396&uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "trackTimeMillis": 3997000,
            "contentAdvisoryRating": "Explicit",
            "genres": [
                {
                    "name": "Comedy",
                    "id": "1303"
                }
            ]
        },
        {
            "previewUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC4365339791.mp3?updated=1739471864",
            "episodeUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC4365339791.mp3?updated=1739471864",
            "artistIds": [],
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "artworkUrl160": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/160x160bb.jpg",
            "episodeFileExtension": "mp3",
            "episodeContentType": "audio",
            "episodeGuid": "e9c3b34e-ea38-11ef-864e-6b084b89e66d",
            "trackId": 1000692224345,
            "trackName": "Yung Gravy",
            "releaseDate": "2025-02-14T12:00:00Z",
            "shortDescription": "",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "closedCaptioning": "none",
            "collectionId": 1440300401,
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "kind": "podcast-episode",
            "wrapperType": "podcastEpisode",
            "description": "Yung Gravy—aka Mr. Clean, aka the Sultan of Sauce—has been serving up smooth flows, retro beats, and more swagger than your mom’s high school prom date. With his signature blend of vintage samples, witty bars, and a voice smoother than butter on a biscuit, Gravy has turned internet virality into a platinum-plated rap career. From Betty (Get Money) to Oops!, his tracks bring the perfect mix of comedy, charisma, and certified bangers. Whether he’s stealing your grandma’s heart or shutting down festival stages, one thing’s for sure—Gravy’s always dripping.\n\n#yunggravy #andrewsantino  #whiskeyginger #podcast\n\n============================================\n\nSponsor Whiskey Ginger: \nhttps://public.liveread.io/media-kit/whiskeyginger\n\nSUPPORT OUR SPONSORS\n\nZOC DOC\nGet local doctors today!\nhttps://zocdoc.com/whiskey\n\nROCKET MONEY\nGET RID OF USELESS\nSUBSCRIPTIONS\nhttp://rocketmoney.com/whiskey\n\nBETTER HELP\n10% OFF YOUR 1ST MONTH\nhttps://betterhelp.com/whiskey\n\nMANDO\n$5 OFF YOUR ORDER WITH\nPROMO CODE: WHISKEY\nhttps://shopmando.com\n\n=======================================\n\nFollow Andrew Santino:\nhttps://www.instagram.com/cheetosantino/\nhttps://twitter.com/CheetoSantino\n\nFollow Whiskey Ginger:\nhttps://www.instagram.com/whiskeygingerpodcast\nhttps://twitter.com/whiskeygingerpodcast\n\nProduced and edited by Joe Faria\nhttps://www.instagram.com/itsjoefaria\nLearn more about your ad choices. Visit megaphone.fm/adchoices",
            "country": "USA",
            "collectionViewUrl": "https://itunes.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?mt=2&uo=4",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/yung-gravy/id1440300401?i=1000692224345&uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "trackTimeMillis": 4789000,
            "contentAdvisoryRating": "Explicit",
            "genres": [
                {
                    "name": "Comedy",
                    "id": "1303"
                }
            ]
        },
        {
            "previewUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC8813368353.mp3?updated=1738802947",
            "episodeUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC8813368353.mp3?updated=1738802947",
            "artistIds": [],
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "artworkUrl160": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/160x160bb.jpg",
            "episodeFileExtension": "mp3",
            "episodeContentType": "audio",
            "episodeGuid": "77f5cb28-e423-11ef-9456-1310d8301c82",
            "trackId": 1000689951563,
            "trackName": "Justin Martindale",
            "releaseDate": "2025-02-07T12:00:00Z",
            "shortDescription": "",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "closedCaptioning": "none",
            "collectionId": 1440300401,
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "kind": "podcast-episode",
            "wrapperType": "podcastEpisode",
            "description": "Justin Martindale is a comedian, writer, and podcaster serving sharp wit with a side of Hollywood tea. A staple at The Comedy Store, he’s got the kind of effortless, cutting humor that makes you say, Did he just say that?—and love him for it. Whether he’s roasting pop culture, riffing on celebrity chaos, or keeping it extra real on his podcast JUST SAYIN’ with Justin Martindale, he brings the perfect mix of sass and smarts. You’ve seen him on E! and heard him slay on the mic—now catch him live before TMZ makes him a headline.\n\n#justinmartindale #andrewsantino  #whiskeyginger #podcast #netflix\n\n============================================\n\nSponsor Whiskey Ginger: \nhttps://public.liveread.io/media-kit/whiskeyginger\n\nSUPPORT OUR SPONSORS\n\nSQUARESPACE\nGet that site up and running now!\n10% off your order\nhttps://squarespace.com/whiskey\n\nPROPHETX\nPROMO CODE: WHISKEY\nGET UP TO $300 IN PROPHET CASH\nhttp://getprophetx.co\n\nHELLO FRESH\nUP TO 10 FREE MEALS\nhttps://hellofresh.com/whiskey10FM\n\nNORD VPN\n4 MONTHS FREE WITH A 2 YEAR PLAN\nhttps://nordvpn.com/whiskey\n\n=======================================\n\nFollow Andrew Santino:\nhttps://www.instagram.com/cheetosantino/\nhttps://twitter.com/CheetoSantino\n\nFollow Whiskey Ginger:\nhttps://www.instagram.com/whiskeygingerpodcast\nhttps://twitter.com/whiskeygingerpodcast\n\nProduced and edited by Joe Faria\nhttps://www.instagram.com/itsjoefaria\nLearn more about your ad choices. Visit megaphone.fm/adchoices",
            "country": "USA",
            "collectionViewUrl": "https://itunes.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?mt=2&uo=4",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/justin-martindale/id1440300401?i=1000689951563&uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "trackTimeMillis": 4130000,
            "contentAdvisoryRating": "Explicit",
            "genres": [
                {
                    "name": "Comedy",
                    "id": "1303"
                }
            ]
        },
        {
            "previewUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC1067007961.mp3?updated=1736801742",
            "episodeUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC1067007961.mp3?updated=1736801742",
            "artistIds": [],
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "artworkUrl160": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/160x160bb.jpg",
            "episodeFileExtension": "mp3",
            "episodeContentType": "audio",
            "episodeGuid": "0d40027a-d1f0-11ef-bcad-b3d53a461d04",
            "trackId": 1000687474992,
            "trackName": "Tim Heidecker",
            "releaseDate": "2025-01-31T12:00:00Z",
            "shortDescription": "",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "closedCaptioning": "none",
            "collectionId": 1440300401,
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "kind": "podcast-episode",
            "wrapperType": "podcastEpisode",
            "description": "Comedian, actor, musician, and absurdist maestro, Tim Heidecker has built a career on making the surreal hilariously real. Best known as one half of the cult comedy duo behind Tim and Eric Awesome Show, Great Job!, Heidecker’s offbeat genius has influenced an entire generation of comedy. Whether he’s lampooning showbiz in On Cinema, exploring existential dread in The Comedy, or crafting tender folk-rock tunes, Tim delivers creativity with a side of chaos. Catch him wherever brilliance meets bizarre—and don’t forget to bring your sense of humor. Check out his podcast Office Hours on YouTube!\n\n#timheidecker #andrewsantino #whiskeyginger #podcast\n\n============================================\n\nSponsor Whiskey Ginger: \nhttps://public.liveread.io/media-kit/whiskeyginger\n\nSUPPORT OUR SPONSORS\n\nROCKET MONEY\nGET RID OF USELESS\nSUBSCRIPTIONS\nhttp://rocketmoney.com/whiskey\n\nKIKOFF\nGET YOUR 1ST MONTH FOR $1\nhttp://getkikoff.com/whiskey\n\nETHOS\nPLANS AS LOW AS $10 A MONTH\nhttp://ethoslife.com/whiskey\n\n=======================================\n\nFollow Andrew Santino:\nhttps://www.instagram.com/cheetosantino/\nhttps://twitter.com/CheetoSantino\n\nFollow Whiskey Ginger:\nhttps://www.instagram.com/whiskeygingerpodcast\nhttps://twitter.com/whiskeygingerpodcast\n\nProduced and edited by Joe Faria\nhttps://www.instagram.com/itsjoefaria\nLearn more about your ad choices. Visit megaphone.fm/adchoices",
            "country": "USA",
            "collectionViewUrl": "https://itunes.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?mt=2&uo=4",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/tim-heidecker/id1440300401?i=1000687474992&uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "trackTimeMillis": 4318000,
            "contentAdvisoryRating": "Explicit",
            "genres": [
                {
                    "name": "Comedy",
                    "id": "1303"
                }
            ]
        },
        {
            "previewUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC5178506480.mp3?updated=1736801399",
            "episodeUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC5178506480.mp3?updated=1736801399",
            "artistIds": [],
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "artworkUrl160": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/160x160bb.jpg",
            "episodeFileExtension": "mp3",
            "episodeContentType": "audio",
            "episodeGuid": "6b3727be-d141-11ef-ab9a-274567a13911",
            "trackId": 1000685295232,
            "trackName": "Fortune Feimster",
            "releaseDate": "2025-01-24T12:00:00Z",
            "shortDescription": "",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "closedCaptioning": "none",
            "collectionId": 1440300401,
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "kind": "podcast-episode",
            "wrapperType": "podcastEpisode",
            "description": "Fortune Feimster is comedy’s ultimate ray of sunshine—hilariously self-deprecating, charmingly Southern, and full of heart. From her Netflix specials (Sweet & Salty and Good Fortune) to scene-stealing roles in The Mindy Project and Life in Pieces, Fortune delivers laughs that feel like a warm hug. A podcast host (Sincerely Fortune), writer, and stand-up powerhouse, she turns relatable moments into unforgettable comedy. Whether she’s dishing out family stories or sharing life lessons, Fortune proves laughter is the best way to bring people together.\n\n#fortunefeimster #andrewsantino #whiskeyginger #podcast\n\n============================================\n\nSponsor Whiskey Ginger: \nhttps://public.liveread.io/media-kit/whiskeyginger\n\nSUPPORT OUR SPONSORS\n\nMANDO\n$5 OFF YOUR ORDER WITH\nPROMO CODE: WHISKEY\nhttps://shopmando.com\n\nSKIMS\nLET THEM KNOW WE SENT YOU!\nhttps://skims.com/whiskey\n\nPROPHETX\nPROMO CODE: WHISKEY\nGET UP TO $300 IN PROPHET CASH\nhttp://getprophetx.co\n\nINDOCHINO\nPROMO CODE: WHISKEY\nGET 20% OFF AN ORDER OF $499 OR MORE!\nhttp://indochino.com\n\n=======================================\n\nFollow Andrew Santino:\nhttps://www.instagram.com/cheetosantino/\nhttps://twitter.com/CheetoSantino\n\nFollow Whiskey Ginger:\nhttps://www.instagram.com/whiskeygingerpodcast\nhttps://twitter.com/whiskeygingerpodcast\n\nProduced and edited by Joe Faria\nhttps://www.instagram.com/itsjoefaria\nLearn more about your ad choices. Visit megaphone.fm/adchoices",
            "country": "USA",
            "collectionViewUrl": "https://itunes.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?mt=2&uo=4",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/fortune-feimster/id1440300401?i=1000685295232&uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "trackTimeMillis": 4193000,
            "contentAdvisoryRating": "Explicit",
            "genres": [
                {
                    "name": "Comedy",
                    "id": "1303"
                }
            ]
        },
        {
            "previewUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC8150671275.mp3?updated=1736726607",
            "episodeUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC8150671275.mp3?updated=1736726607",
            "artistIds": [],
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "artworkUrl160": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/160x160bb.jpg",
            "episodeFileExtension": "mp3",
            "episodeContentType": "audio",
            "episodeGuid": "1d02d728-d141-11ef-a90b-d7dc28667957",
            "trackId": 1000684373792,
            "trackName": "Ari Shaffir",
            "releaseDate": "2025-01-17T12:00:00Z",
            "shortDescription": "",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "closedCaptioning": "none",
            "collectionId": 1440300401,
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "kind": "podcast-episode",
            "wrapperType": "podcastEpisode",
            "description": "Ari Shaffir is a boundary-pushing comedian, storyteller, and provocateur who isn’t afraid to say what you’re thinking—or what you’re scared to think. Known for his fearless, uncensored specials (Ari Shaffir: Jew), hit podcast (Skeptic Tank), and appearances on This Is Not Happening, Ari crafts comedy that’s as thought-provoking as it is hilarious. When he’s not on stage or behind the mic, he’s probably traveling, stirring the pot, or finding new ways to embrace the absurdity of life. Catch him live and find out why no topic is off-limits! Check out Ari's new special America's Sweetheart out now on Netflix!!\n\n#arishaffir #americassweetheart #andrewsantino  #whiskeyginger #podcast #netflix\n\n============================================\n\nSponsor Whiskey Ginger: \nhttps://public.liveread.io/media-kit/whiskeyginger\n\nSUPPORT OUR SPONSORS\n\nSQUARESPACE\nGet that site up and running now!\n10% off your order\nhttps://squarespace.com/whiskey\n\nBETTER HELP\n10% OFF YOUR 1ST MONTH\nhttps://betterhelp.com/whiskey\n\n=======================================\n\nFollow Andrew Santino:\nhttps://www.instagram.com/cheetosantino/\nhttps://twitter.com/CheetoSantino\n\nFollow Whiskey Ginger:\nhttps://www.instagram.com/whiskeygingerpodcast\nhttps://twitter.com/whiskeygingerpodcast\n\nProduced and edited by Joe Faria\nhttps://www.instagram.com/itsjoefaria\nLearn more about your ad choices. Visit megaphone.fm/adchoices",
            "country": "USA",
            "collectionViewUrl": "https://itunes.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?mt=2&uo=4",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/ari-shaffir/id1440300401?i=1000684373792&uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "trackTimeMillis": 4147000,
            "contentAdvisoryRating": "Explicit",
            "genres": [
                {
                    "name": "Comedy",
                    "id": "1303"
                }
            ]
        },
        {
            "previewUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC6755069427.mp3?updated=1736726532",
            "episodeUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC6755069427.mp3?updated=1736726532",
            "artistIds": [],
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "artworkUrl160": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/160x160bb.jpg",
            "episodeFileExtension": "mp3",
            "episodeContentType": "audio",
            "episodeGuid": "59eadf44-ceb4-11ef-922b-27481476096e",
            "trackId": 1000683460646,
            "trackName": "Jiaoying Summers",
            "releaseDate": "2025-01-10T12:00:00Z",
            "shortDescription": "",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "closedCaptioning": "none",
            "collectionId": 1440300401,
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "kind": "podcast-episode",
            "wrapperType": "podcastEpisode",
            "description": "Jiaoying Summers is a comedy powerhouse making waves with her unapologetic humor and electric stage presence. Born in China and now dominating the U.S. comedy scene, Jiaoying turns cultural clashes and personal struggles into laugh-out-loud gold. A regular at the Comedy Store and Laugh Factory, she’s also a viral sensation with millions of fans across TikTok and Instagram. Bold, brilliant, and fiercely original, Jiaoying’s voice is one you won’t forget. Catch her live https://summerscomedy.com/ or online—either way, she’ll leave you in stitches.\n\n#jiaoyingsummers #andrewsantino #whiskeyginger #podcasts #comedy \n\n============================================\n\nSponsor Whiskey Ginger: \nhttps://public.liveread.io/media-kit/whiskeyginger\n\nSUPPORT OUR SPONSORS\n\nZOCDOC\nBOOK LOCAL DOCTORS\nhttp://zocdoc.com/whiskey\n\nROCKET MONEY\nGET RID OF USELESS\nSUBSCRIPTIONS\nhttp://rocketmoney.com/whiskey\n\nPROPHETX\nPROMO CODE: WHISKEY\nGET UP TO $300 IN PROPHET CASH\nhttp://getprophetx.co\n\n=======================================\n\nFollow Andrew Santino:\nhttps://www.instagram.com/cheetosantino/\nhttps://twitter.com/CheetoSantino\n\nFollow Whiskey Ginger:\nhttps://www.instagram.com/whiskeygingerpodcast\nhttps://twitter.com/whiskeygingerpodcast\n\nProduced and edited by Joe Faria\nhttps://www.instagram.com/itsjoefaria\nLearn more about your ad choices. Visit megaphone.fm/adchoices",
            "country": "USA",
            "collectionViewUrl": "https://itunes.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?mt=2&uo=4",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/jiaoying-summers/id1440300401?i=1000683460646&uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "trackTimeMillis": 3987000,
            "contentAdvisoryRating": "Explicit",
            "genres": [
                {
                    "name": "Comedy",
                    "id": "1303"
                }
            ]
        },
        {
            "previewUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC7570611460.mp3?updated=1735861775",
            "episodeUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC7570611460.mp3?updated=1735861775",
            "artistIds": [],
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "artworkUrl160": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/160x160bb.jpg",
            "episodeFileExtension": "mp3",
            "episodeContentType": "audio",
            "episodeGuid": "23a0c120-c959-11ef-9521-bb037d970747",
            "trackId": 1000682529096,
            "trackName": "Ian Fidance & Jordan Jensen",
            "releaseDate": "2025-01-03T12:00:00Z",
            "shortDescription": "",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "closedCaptioning": "none",
            "collectionId": 1440300401,
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "kind": "podcast-episode",
            "wrapperType": "podcastEpisode",
            "description": "Ian Fidance is a wild card of comedy—an offbeat powerhouse blending high-octane energy with razor-sharp wit. Hailing from Delaware and now tearing up the NYC comedy scene, Ian's quicksilver crowd work and deeply personal bits leave audiences howling.  Jordan Jensen is the down-to-earth dynamo flipping stand-up comedy on its head. With her no-nonsense storytelling and killer punchlines, she blends raw honesty with a unique voice that’s earned her a spot as one of New York's rising stars. \n\n#ianandjordan #andrewsantino #whiskeyginger #podcast\n\n============================================\n\nSponsor Whiskey Ginger: \nhttps://public.liveread.io/media-kit/whiskeyginger\n\nSUPPORT OUR SPONSORS\n\nBIOPTIMIZERS\nPROMO CODE: WHISKEY\n25% OFF YOUR ORDER\nhttp://bioptimizers.com/whiskey\n\nVERSO\nPROMO CODE: WHISKEY\n15% OFF YOUR 1ST ORDER\nhttp://ver.so\n\nKIKOFF\nGET YOUR 1ST MONTH FOR $1\nhttp://getkikoff.com/whiskey\n\nSQUARESPACE\nGet that site up and running now!\n10% off your order\nhttps://squarespace.com/whiskey\n\n=======================================\n\nFollow Andrew Santino:\nhttps://www.instagram.com/cheetosantino/\nhttps://twitter.com/CheetoSantino\n\nFollow Whiskey Ginger:\nhttps://www.instagram.com/whiskeygingerpodcast\nhttps://twitter.com/whiskeygingerpodcast\n\nProduced and edited by Joe Faria\nhttps://www.instagram.com/itsjoefaria\nLearn more about your ad choices. Visit megaphone.fm/adchoices",
            "country": "USA",
            "collectionViewUrl": "https://itunes.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?mt=2&uo=4",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/ian-fidance-jordan-jensen/id1440300401?i=1000682529096&uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "trackTimeMillis": 3853000,
            "contentAdvisoryRating": "Explicit",
            "genres": [
                {
                    "name": "Comedy",
                    "id": "1303"
                }
            ]
        },
        {
            "previewUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC1094422940.mp3?updated=1735161692",
            "episodeUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC1094422940.mp3?updated=1735161692",
            "artistIds": [],
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "artworkUrl160": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/160x160bb.jpg",
            "episodeFileExtension": "mp3",
            "episodeContentType": "audio",
            "episodeGuid": "1c1eb6b8-c301-11ef-a12d-730eb3633c5e",
            "trackId": 1000681850739,
            "trackName": "Adrienne Iapalucci",
            "releaseDate": "2024-12-27T12:00:00Z",
            "shortDescription": "",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "closedCaptioning": "none",
            "collectionId": 1440300401,
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "kind": "podcast-episode",
            "wrapperType": "podcastEpisode",
            "description": "Adrienne Iapalucci: Darkly hilarious and unapologetically sharp, Adrienne delivers comedy that leaves audiences laughing—and sometimes gasping. Known for her biting wit and fearless takes, she’s been featured on The Degenerates on Netflix, crushed on The Late Show with David Letterman, and has a podcast, Vadge. Don’t miss your chance to see her live—grab your tickets at https://adrienneIapalucci.com\n\n#adrienneiapalucci #andrewsantino #whiskeyginger #darkqueen #podcast\n\n============================================\n\nSponsor Whiskey Ginger: \nhttps://public.liveread.io/media-kit/whiskeyginger\n\nSUPPORT OUR SPONSORS\n\nMANDO\nUse Promo Code: WHISKEY\nFOR $5 OFF YOUR ORDER\nhttp://shopmando.com\n\nPRIZEPICKS\nDownload The App!\nUSE PROMO CODE: WHISKEY\nGET $50 INSTANTLY WITH YOUR 1ST $5 BET\n\n=======================================\n\nFollow Andrew Santino:\nhttps://www.instagram.com/cheetosantino/\nhttps://twitter.com/CheetoSantino\n\nFollow Whiskey Ginger:\nhttps://www.instagram.com/whiskeygingerpodcast\nhttps://twitter.com/whiskeygingerpodcast\n\nProduced and edited by Joe Faria\nhttps://www.instagram.com/itsjoefaria\nLearn more about your ad choices. Visit megaphone.fm/adchoices",
            "country": "USA",
            "collectionViewUrl": "https://itunes.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?mt=2&uo=4",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/adrienne-iapalucci/id1440300401?i=1000681850739&uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "trackTimeMillis": 4328000,
            "contentAdvisoryRating": "Explicit",
            "genres": [
                {
                    "name": "Comedy",
                    "id": "1303"
                }
            ]
        },
        {
            "previewUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC1928402337.mp3?updated=1734576526",
            "episodeUrl": "https://www.podtrac.com/pts/redirect.mp3/pdst.fm/e/pscrb.fm/rss/p/claritaspod.com/measure/mgln.ai/e/27/traffic.megaphone.fm/TPC1928402337.mp3?updated=1734576526",
            "artistIds": [],
            "artworkUrl600": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/600x600bb.jpg",
            "artworkUrl160": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/160x160bb.jpg",
            "episodeFileExtension": "mp3",
            "episodeContentType": "audio",
            "episodeGuid": "10f84e1e-bdb3-11ef-b892-53fcaed3a033",
            "trackId": 1000681119955,
            "trackName": "Matt McCusker",
            "releaseDate": "2024-12-20T12:00:00Z",
            "shortDescription": "",
            "feedUrl": "https://feeds.megaphone.fm/TPC6596839207",
            "closedCaptioning": "none",
            "collectionId": 1440300401,
            "collectionName": "Whiskey Ginger with Andrew Santino",
            "kind": "podcast-episode",
            "wrapperType": "podcastEpisode",
            "description": "Matt McCusker joins the show! What a great hang with one of our favorite Philly animals. Settle in for a great episode with one of the top g's in comedy. Be sure to check out Matt on tour. https://mattmccusker.com/\n\n#mattmccusker #andrewsantino #whiskeyginger #mattandshane #podcast\n\n============================================\n\nSponsor Whiskey Ginger: \nhttps://public.liveread.io/media-kit/whiskeyginger\n\nSUPPORT OUR SPONSORS\n\nSQUARESPACE\nGet that site up and running now!\n10% off your order\nhttps://squarespace.com/whiskey\n\nBETTER HELP\n10% OFF YOUR 1ST MONTH\nhttps://betterhelp.com/whiskey\n\nPDS DEBT\nGET YOUR FREE DEBT ANALYSIS\nhttp://pdsdebt.com/whiskey\n\nBIOPTIMIZERS\nPROMO CODE: WHISKEY\n25% OFF YOUR ORDER\nhttp://bioptimizers.com/whiskey\n\n=======================================\n\nFollow Andrew Santino:\nhttps://www.instagram.com/cheetosantino/\nhttps://twitter.com/CheetoSantino\n\nFollow Whiskey Ginger:\nhttps://www.instagram.com/whiskeygingerpodcast\nhttps://twitter.com/whiskeygingerpodcast\n\nProduced and edited by Joe Faria\nIG: @itsjoefaria\nLearn more about your ad choices. Visit megaphone.fm/adchoices",
            "country": "USA",
            "collectionViewUrl": "https://itunes.apple.com/us/podcast/whiskey-ginger-with-andrew-santino/id1440300401?mt=2&uo=4",
            "trackViewUrl": "https://podcasts.apple.com/us/podcast/matt-mccusker/id1440300401?i=1000681119955&uo=4",
            "artworkUrl60": "https://is1-ssl.mzstatic.com/image/thumb/Podcasts112/v4/c2/67/7b/c2677be5-e64e-168d-ead2-c813769ed420/mza_9468318625889443460.jpg/60x60bb.jpg",
            "trackTimeMillis": 5236000,
            "contentAdvisoryRating": "Explicit",
            "genres": [
                {
                    "name": "Comedy",
                    "id": "1303"
                }
            ]
        }
    ]
}